# Generated by Django 2.2.3 on 2019-07-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itedepartmentfaculty',
            name='lastname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itedepartmentfaculty',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
