# Generated by Django 2.2.3 on 2019-07-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190708_0429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IteDepartmentFaculty',
            new_name='IteDepartmentFaculties',
        ),
    ]
