# Generated by Django 2.2.3 on 2019-07-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190708_0523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IteDepartmentFaculties',
            new_name='FacultyIteDepartment',
        ),
    ]
