# Generated by Django 2.2.4 on 2019-08-14 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_facultyhrmdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyhrmdepartment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='facultyitedepartment',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
    ]
