# Generated by Django 2.2.4 on 2019-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190814_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_photo', models.ImageField(blank=True, null=True, upload_to='img')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
