# Generated by Django 2.2.4 on 2019-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAndStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('department_or_office', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='img')),
            ],
        ),
    ]
