# Generated by Django 2.2.4 on 2019-08-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyHrmDepartment',
        ),
        migrations.DeleteModel(
            name='FacultyIteDepartment',
        ),
        migrations.AlterField(
            model_name='facultyandstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
