# Generated by Django 2.2.4 on 2019-08-31 04:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190831_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='member',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='pages.FacultyAndStaff'),
            preserve_default=False,
        ),
    ]
