# Generated by Django 2.2.4 on 2019-08-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_department_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='member',
        ),
        migrations.AlterField(
            model_name='facultyandstaff',
            name='department_or_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Department'),
        ),
    ]
