# Generated by Django 2.2.4 on 2019-08-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190831_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyandstaff',
            name='department_or_office',
            field=models.CharField(max_length=200),
        ),
    ]
