# Generated by Django 2.2.4 on 2019-09-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20190831_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('department_or_office', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='pages.Department')),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyAndStaff',
        ),
    ]
