# Generated by Django 2.2.4 on 2019-09-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20190902_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department_or_office',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='job_description',
        ),
    ]
