# Generated by Django 2.2.5 on 2019-09-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
