# Generated by Django 2.2.5 on 2019-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_staffmember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
