# Generated by Django 2.2.5 on 2019-09-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20190923_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='map_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
