# Generated by Django 2.2.5 on 2019-09-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_frequentlyaskedquestion_map_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmap',
            name='map_discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
