# Generated by Django 2.2.5 on 2019-09-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_schoolmap_map_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolmap',
            old_name='map_discription',
            new_name='map_description',
        ),
    ]
